{{
    stop(id: "{input_stop_id}") {{
        name
        stoptimesWithoutPatterns {{
            scheduledArrival
            realtimeArrival
            arrivalDelay
            scheduledDeparture
            realtimeDeparture
            departureDelay
            realtime
            realtimeState
            serviceDay
            headsign
            trip {{
                routeShortName
            }}
        }}
    }}
}}