{{
    stop(id: "{input_stop_id}") {{
        stoptimesWithoutPatterns {{
            headsign
            trip {{
                routeShortName
            }}
            scheduledDeparture
            realtimeDeparture
            serviceDay
        }}
    }}
}}